---
title: Hitchens
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: hello@patdryburgh.com
description: An inarguably well-designed Jekyll theme.
baseurl: "/hitchens"
url: https://patdryburgh.github.io
icon: "/assets/images/icon-512.png"
twitter_username: patdryburgh
github_username: patdryburgh
markdown: kramdown
plugins:
- jekyll-paginate
paginate: 3
paginate_path: "/page/:num/"
